#!/usr/bin/env python3

N = int(input())
nums = [int(i) for i in input().split()]

if all(nums) > 0:
    if any(str(x) == str(x)[::-1] for x in nums):
            print("True")
else:
    print('False')
