#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(input().strip())

divs = []    
for i in range(1,n+1):
    if n % i == 0:
        divs.append(i)

fav = 1 
dig_sum = 1       
for d in divs:
    tmp = 0
    for ch in str(d):
        tmp += int(ch)
    if tmp > dig_sum:
        dig_sum = tmp
        fav = d
        
print(fav)
        
