#!/usr/bin/env python3

A = set(map(int, input().strip().split()))
n = int(input())
flag = True
for _ in range(n):
    N = set(map(int, input().strip().split()))
    #N = {int(i) for i in input().strip().split()}
    
    for i in N:
        if i not in A:
            flag = False
            break        
print(flag)
