#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'solve' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER r
#  3. INTEGER m
#


def solve(n, r, m):

    #r and n-r either way 
    if r == n-r:
        a,b = r,n-r
    else:
        a,b = min(r, n-r), max(r, n-r)
    
    afact = 1
    for i in range(1, a+1):
        afact *= i
        
    bfact = afact
    if b>a:
        for i in range(a+1, b+1):
            bfact *= i
    
    nfact = bfact
    if n>b:
        for i in range(b+1, n+1):
            nfact *= i    
    
    nCr = nfact // (afact * bfact)
    return nCr % m
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input().strip())

    for t_itr in range(t):
        first_multiple_input = input().rstrip().split()

        n = int(first_multiple_input[0])

        r = int(first_multiple_input[1])

        m = int(first_multiple_input[2])

        result = solve(n, r, m)

        fptr.write(str(result) + '\n')

    fptr.close()
