#!/usr/bin/env python3

from collections import deque

d = deque()
n = int(input().strip())
for _ in range(n):
    c = input().strip().split()
    #print(c)
    if c[0] == "append":
        d.append(c[1])
    elif c[0] == "appendleft":
        d.appendleft(c[1])
    elif c[0] == "pop":
        d.pop()
    elif c[0] == "popleft":
        d.popleft()

print(" ".join(d))
        
    
