#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    
    s = input()
    d = {}
    
    for ch in s:
        if ch in d:
            d[ch] += 1
        else:
            d[ch] = 1
            
    desc_d = sorted(d.items(),key=lambda x:(-x[1],x[0]))
        
    for i in range(3):
        pair = desc_d[i]
        
        print(pair[0], pair[1])
        
