#!/bin/python3

import math
import os
import random
import re
import sys
import string
#
# Complete the 'happyLadybugs' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING b as parameter.
#

def happyLadybugs(b):
    # string.ascii_uppercase
    
    uniq = set(b)
    for u in uniq:
        if u in string.ascii_uppercase:
            if b.count(u) < 2:
                return "NO"
            elif "_" not in b:
                for i in range(len(b)):
                    if i==0:
                        if b[0] != b[1]:
                            return "NO"
                    elif i == len(b) -1:
                        if b[-1] != b[-2]:
                            return "NO"
                    else:
                        if b[i] != b[i-1] and b[i] != b[i+1]:
                            return "NO"
                            
    return "YES"
                
            
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    g = int(input().strip())

    for g_itr in range(g):
        n = int(input().strip())

        b = input()

        result = happyLadybugs(b)

        fptr.write(result + '\n')

    fptr.close()
