#!/bin/python3

import math
import os
import random
import re
import sys
import datetime


def libraryFine(d1, m1, y1, d2, m2, y2):
    
    returned = datetime.datetime(y1,m1,d1)
    due = datetime.datetime(y2,m2,d2)
    
    if returned <= due:
        fine = 0
    elif m1 == m2 and y1 == y2:
        fine = 15 * (d1-d2)
    elif y1 == y2:
        fine = 500 * (m1-m2)
    else:
        fine = 10000
        
    return fine
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    d1 = int(first_multiple_input[0])

    m1 = int(first_multiple_input[1])

    y1 = int(first_multiple_input[2])

    second_multiple_input = input().rstrip().split()

    d2 = int(second_multiple_input[0])

    m2 = int(second_multiple_input[1])

    y2 = int(second_multiple_input[2])

    result = libraryFine(d1, m1, y1, d2, m2, y2)

    fptr.write(str(result) + '\n')

    fptr.close()
    
