#!/usr/bin/env python3

cube = lambda x : x**3

def fibonacci(n):
    if n==0:
        return[]
    if n==1:
        return[0]
    ans = [0,1]
    for i in range(2, n):
        ans.append(ans[i-2]+ans[i-1])
    return ans       

if __name__ == '__main__':
    n = int(input())
    print(list(map(cube, fibonacci(n))))
