#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'marsExploration' function below.
#
# The function is expected to return an INTEGER.
# The function accepts STRING s as parameter.
#

def marsExploration(s):
    
    ls = [s[i:i+3] for i in range(0, len(s), 3)]
    ct = 0
    for el in ls:
        if el[0] != "S":
            ct += 1
        if el[1] != "O":
            ct += 1
        if el[2] != "S":
            ct += 1
    return ct
        
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = marsExploration(s)

    fptr.write(str(result) + '\n')

    fptr.close()
