#!/usr/bin/env python3

n, m = map(int, input().strip().split())
arr = input().strip().split()
like = input().strip().split()
dislike = input().strip().split()

set_arr = set(arr)
set_like = set_arr and like
set_dislike = set_arr and dislike

h = 0 #init happiness
for a in arr:
    if a in set_like:
        h += 1
    elif a in set_dislike:
        h -= 1
              
print(h)

