#!/usr/bin/env python3

from collections import OrderedDict
import re

d = OrderedDict()
n = int(input().strip())

for ln in range(n):
    
    item_name, net_price = input().strip().rsplit(" ", 1)
    
    d[item_name] = d.get(item_name, 0) + int(net_price)
  
for k,v in d.items():
    print(k,v)
    
