#!/usr/bin/env python3


t = int(input())
for _ in range(t):
    n = input()
    blocks = list(map(int, input().split()))

    res = "Yes"
    prev = ""
    while len(blocks) > 0:
        if len(blocks) == 1:
            mx = blocks[0]
            blocks.pop()
        elif blocks[0] >= blocks[-1]:
            mx = blocks[0]
            blocks.pop(0)
        else:
            mx = blocks[-1]
            blocks.pop()
        
        if prev == "":
            prev = mx
        else:
            if prev >= mx:
                prev = mx
            else:
                res = "No"
    print(res)
          
