#!/bin/python3

import math
import os
import random
import re
import sys

#
# The function is expected to return a LONG_INTEGER.
# The function accepts following parameters:
#  1. STRING s
#  2. LONG_INTEGER n
#

def repeatedString(s, n):
    
    s_reps = n // len(s)
    n_rem = n % len(s)
    s_part = s[:n_rem]
    a_in_s = 0
    a_in_s_part = 0
    for i in range(len(s)):
        if s[i] == "a":
            a_in_s += 1
            if i in range(len(s_part)):
                a_in_s_part +=1
    
    total_a = (a_in_s) * s_reps + a_in_s_part
    return total_a     
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    n = int(input().strip())

    result = repeatedString(s, n)

    fptr.write(str(result) + '\n')

    fptr.close()
