#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':

    arr = []

    for _ in range(6):
        arr.append(list(map(int, input().rstrip().split())))

        
row_count = len(arr)
col_count = len(arr[0])

max_score = "mada"

for i in range(col_count - 2):
    for j in range(row_count - 2):
        score = arr[i][j] + arr[i][j+1] + arr[i][j+2] + arr[i+1][j+1] + arr[i+2][j] + arr[i+2][j+1] + arr[i+2][j+2]
        
        if max_score == "mada" or score > max_score:
            max_score = score
            
print(max_score)
        
        
        
    
    
