#!/usr/bin/env python3


n = int(input().strip())
english = set(map(int, input().strip().split()))
n = int(input().strip())
french = set(map(int, input().strip().split()))

both = english.intersection(french)

print(len(both))
