#!/usr/bin/env python3

n = int(input())
s = set(map(int, input().split()))
nc = int(input())
for _ in range(nc):
    c = input().split()
    if c[0] == "discard":
        s.discard(int(c[1]))
    elif c[0] == "remove":
        s.remove(int(c[1]))
    elif c[0] == "pop":
        s.pop()
print(sum(s))
