#!/usr/bin/env python3


n = int(input().strip())
english = set(map(int, input().strip().split()))
n = int(input().strip())
french = set(map(int, input().strip().split()))

eng_only= english.difference(french)

print(len(eng_only))
