#!/bin/python3

import math
import os
import random
import re
import sys
import collections
#
# Complete the 'solve' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY a as parameter.
#

def solve(a):
    pairs = 0
    counter = collections.Counter(a)
    for num in counter:
        if counter[num] > 1:   #1>>0, 2>>2, 3>>6, 4>>12
            pairs += (counter[num] * (counter[num]-1))     
    return pairs
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input().strip())

    for t_itr in range(t):
        a_count = int(input().strip())

        a = list(map(int, input().rstrip().split()))

        result = solve(a)

        fptr.write(str(result) + '\n')

    fptr.close()
