#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'solve' function below.
#
# The function is expected to return a STRING.
# The function accepts INTEGER n as parameter.
#

def solve(n):
    arr = [9]
    new = []
    while n:
        for a in arr:
            if a % n == 0:
                return str(a)
            else:
                new.append(int(str(a)+"0"))
                new.append(int(str(a)+"9"))
        arr = new
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input().strip())

    for t_itr in range(t):
        n = int(input().strip())

        result = solve(n)

        fptr.write(result + '\n')

    fptr.close()
