#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'superReducedString' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def superReducedString(s):
    
    p = 0
    while p in range(len(s)-1):
        if s[p]==s[p+1]:
            s = s[:p] + s[p+2:]
            p = max(0, p-1)
        else:
            p += 1
    
    if len(s) > 0:
        return s    
    else:
        return "Empty String"
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = superReducedString(s)

    fptr.write(result + '\n')

    fptr.close()
