#!/usr/bin/env python3

M = int(input().strip())
m = set(input().strip().split())
N = int(input().strip())
n = set(input().strip().split())

dif = m.symmetric_difference(n)
x = sorted(dif, key = int) 
for i in x:
    print(i)
