#!/usr/bin/env python3


n = int(input().strip())
english = set(map(int, input().strip().split()))
n = int(input().strip())
french = set(map(int, input().strip().split()))

either_or = english.symmetric_difference(french)

print(len(either_or))
