#!/usr/bin/env python3

import math

class Points(object):
    def __init__(self, x, y, z):
        self.x = x
        self.y = y
        self.z = z
        
    def __sub__(self, no):
        px = self.x - no.x
        py = self.y - no.y
        pz = self.z - no.z
        return Points(px, py, pz)

    def dot(self, no):
        px = self.x * no.x
        py = self.y * no.y
        pz = self.z * no.z
        return px + py + pz

    def cross(self, no):
        p1 = self.y * no.z - self.z * no.y
        p2 = self.x * no.z - self.z * no.x
        p3 = self.x * no.y - self.y * no.x
        return Points(p1, p2, p3)
        
    def absolute(self):
        return pow((self.x ** 2 + self.y ** 2 + self.z ** 2), 0.5)

if __name__ == '__main__':
    points = list()
    for i in range(4):
        a = list(map(float, input().split()))
        points.append(a)

    a, b, c, d = Points(*points[0]), Points(*points[1]), Points(*points[2]), Points(*points[3])
    x = (b - a).cross(c - b)
    y = (c - b).cross(d - c)
    angle = math.acos(x.dot(y) / (x.absolute() * y.absolute()))

    print("%.2f" % math.degrees(angle))
